// Site content: services, projects, guides and their supporting data.
// Moved verbatim from app/[...slug]/page.tsx so each page composition can import it.
export const origin = "https://abdullahbuilt.top";
export const updated = "2026-09-27";

export type Service = {
  slug: string; name: string; title: string; description: string;
  signals: string[]; deliverables: string[]; related: string[];
};

export type Guide = {
  slug:string; category:string; service:string; proof:string[]; title:string;
  description:string; intro:string; sections:[string,string][]; published?:string;
};

export const services: Service[] = [
  { slug:"custom-software-development", name:"Custom Software Development", title:"Custom Software Development Services for real workflows", description:"Turn a business problem, manual workflow, or difficult requirement into software that people can use and maintain.", signals:["A spreadsheet, inbox, or manual handoff is carrying an important workflow.","An existing tool cannot reflect how your team actually makes decisions.","A feature needs thoughtful product design as well as implementation."], deliverables:["Internal operations tools and workflow systems","Customer-facing application features and portals","Data-backed dashboards with clear actions","Payments, identity, notifications, and external-service integrations"], related:["saas-development","web-application-development","api-integration-development"] },
  { slug:"saas-development", name:"SaaS Development", title:"SaaS Product Development Services for a useful first release", description:"Build a SaaS application around the job a customer needs done, then make the account, data, interface, and operating workflow work together.", signals:["You have a clear customer problem but need the first application shaped and built.","A prototype proves interest but cannot support real users or reliable data.","Your team needs a focused engineer who can own the critical path to launch."], deliverables:["Multi-page SaaS applications and dashboards","Authentication, roles, data models, and account flows","Billing or payment-adjacent workflows where appropriate","Admin views, feedback loops, and release-ready deployment"], related:["custom-software-development","web-application-development","mvp-product-development"] },
  { slug:"web-application-development", name:"Web Application Development", title:"Web Application Development Services for dependable user workflows", description:"Create web applications that help users finish a real task, with an interface that makes complex systems understandable.", signals:["Your work needs more than a brochure site or isolated UI mockup.","A workflow has several states, users, permissions, or data sources.","The team needs a responsive front end connected to dependable application logic."], deliverables:["Dashboards, portals, and operational consoles","Responsive React and Next.js interfaces","Search, filters, tables, charts, and action-driven workflows","Accessible page structure with practical loading and error states"], related:["custom-software-development","saas-development","api-integration-development"] },
  { slug:"api-integration-development", name:"API Integration Development", title:"API Integration Services for connected, reliable systems", description:"Connect the systems your application depends on without hiding important states, constraints, and failure paths.", signals:["Users copy information between tools or wait for manual updates.","An application needs to consume external data or trigger another system.","An existing integration is unreliable, opaque, or difficult to extend."], deliverables:["REST APIs, webhooks, and third-party service connections","Data synchronization and event-driven workflows","Payment and blockchain-connected application components","Validation, retries, clear error states, and audit-friendly records"], related:["custom-software-development","business-automation","web-application-development"] },
  { slug:"business-automation", name:"Business Automation & Internal Tools", title:"Business Process Automation Services with visible control", description:"Make recurring work easier to run, inspect, and recover without hiding approvals, exceptions, or operational ownership.", signals:["A repeatable task consumes time because information is scattered.","Operations depend on one person remembering the next step.","Teams need a controlled workflow rather than a fragile chain of manual updates."], deliverables:["Internal tools for tracking, triage, approvals, and handoffs","Workflow automation around APIs, forms, and GitHub","Operational dashboards with useful decision context","Verification and review flows for high-accountability work"], related:["custom-software-development","api-integration-development","mvp-product-development"] },
  { slug:"mvp-product-development", name:"MVP Product Development", title:"MVP Product Development for a complete learning loop", description:"Shape and build the smallest complete product workflow that real users can try and your team can learn from.", signals:["An idea needs a working release rather than another deck or prototype.","The team needs to separate critical product assumptions from future features.","A first version must connect real data, users, and operational constraints."], deliverables:["Critical-path product definition and user-flow mapping","A focused web application with real data boundaries","Authentication and essential third-party integrations","Testing, deployment, handoff, and an evidence-led next scope"], related:["saas-development","custom-software-development","web-application-development"] },
  { slug:"ai-application-development", name:"AI Application & Agent Development", title:"AI Application Development Services for controlled workflows", description:"Build AI applications and agent workflows that connect models to real data, scoped tools, review steps, and measurable product outcomes.", signals:["A useful workflow needs model reasoning without giving up control or traceability.","An existing product needs an AI feature connected to its real data and permissions.","A repetitive research, support, or operations task needs tool use and human review."], deliverables:["AI-assisted web applications and product features","Agent workflows with explicit tools, permissions, and approval points","Retrieval and structured-data integrations","Evaluation, fallback, observability, and cost controls"], related:["business-automation","api-integration-development","saas-development"] },
  { slug:"product-rescue", name:"Product Rescue & Stabilization", title:"Product Rescue for software that needs a reliable path forward", description:"Diagnose a stalled, fragile, or AI-built product, stabilize the critical workflow, and leave the codebase easier to operate and extend.", signals:["A prototype works in a demo but fails under real use.","The team cannot confidently release because errors, ownership, or scope are unclear.","AI-assisted changes have accumulated faster than the codebase can be reviewed and trusted."], deliverables:["Critical-path product and codebase assessment","Reproducible defect and risk inventory","Focused fixes for reliability, data, integrations, and release flow","Verification evidence, deployment notes, and a prioritized recovery plan"], related:["custom-software-development","web-application-development","api-integration-development"] },
];

// Human-facing service copy. Never derive these by lower-casing names ("ai", "a ai", "saas").
export type ServiceCopy = { displayName:string; ctaShort:string; ctaLong:string; ctaHeading:string; faqHeading:string };
export const serviceCopy: Record<string,ServiceCopy> = {
  "custom-software-development":{displayName:"custom software development",ctaShort:"Discuss custom software",ctaLong:"Start a custom software development inquiry",ctaHeading:"Discuss your custom software project.",faqHeading:"Questions about custom software development"},
  "saas-development":{displayName:"SaaS development",ctaShort:"Discuss a SaaS build",ctaLong:"Start a SaaS development inquiry",ctaHeading:"Discuss your SaaS product.",faqHeading:"Questions about SaaS development"},
  "web-application-development":{displayName:"web application development",ctaShort:"Discuss a web application",ctaLong:"Start a web application development inquiry",ctaHeading:"Discuss your web application.",faqHeading:"Questions about web application development"},
  "api-integration-development":{displayName:"API integration development",ctaShort:"Discuss an API integration",ctaLong:"Start an API integration development inquiry",ctaHeading:"Discuss the integration that has to hold up.",faqHeading:"Questions about API integration"},
  "business-automation":{displayName:"business automation and internal tools",ctaShort:"Discuss an automation",ctaLong:"Start a business automation inquiry",ctaHeading:"Discuss the workflow you want to automate.",faqHeading:"Questions about business automation and internal tools"},
  "mvp-product-development":{displayName:"MVP product development",ctaShort:"Discuss an MVP",ctaLong:"Start an MVP development inquiry",ctaHeading:"Discuss your MVP.",faqHeading:"Questions about MVP development"},
  "ai-application-development":{displayName:"AI application and agent development",ctaShort:"Discuss an AI application",ctaLong:"Start an AI application development inquiry",ctaHeading:"Discuss your AI application or agent workflow.",faqHeading:"Questions about AI applications and agents"},
  "product-rescue":{displayName:"product rescue and stabilization",ctaShort:"Discuss a product rescue",ctaLong:"Start a product rescue inquiry",ctaHeading:"Discuss the product that needs stabilizing.",faqHeading:"Questions about product rescue"},
};

export const projects = [
  { slug:"resolve", name:"RESOLVE", subtitle:"Programmable economy infrastructure", description:"Outcome-backed payments infrastructure for verified contributions, funding workflows, attribution, treasury, and USDC settlement.", context:"RESOLVE explores how verified work can move through funding and settlement workflows. It frames contribution evidence, attribution, treasury, and escrow as connected parts of an outcome-backed payment system.", built:"The product brings contribution evidence, funding states, attribution, and USDC settlement into one surface, making the path from verified input to a funding decision inspectable.", architecture:"Next.js provides the application layer. Supabase, Postgres, and Prisma support structured records. AI-assisted components support the workflow while wallet and Arc settlement steps remain explicit.", decisions:["Keep verified contributions and settlement states visible.","Use a relational layer for structured, inspectable records.","Keep model-assisted features around deterministic product logic."], live:"https://resolve-task.vercel.app/", code:"https://github.com/velz-cmd/Things-to-do" },
  { slug:"meridian", name:"MERIDIAN", subtitle:"Market intelligence OS", description:"A market intelligence OS connecting market data, explainable strategy rules, historical replay, and optional execution.", context:"MERIDIAN asks how market data can become a strategy a user can inspect, debate, and replay rather than a black-box signal.", built:"The product combines market data, deterministic skills, opposing analysis, strategy constraints, historical replay, and optional execution in one legible workflow.", architecture:"Next.js and TypeScript separate data inputs, strategy rules, analysis, constraints, and replay so every stage has a clear role.", decisions:["Put explainability and replay beside the strategy workflow.","Use deterministic skills where predictable behavior matters.","Keep execution distinct from research and decision preparation."], live:"https://trader-arc.vercel.app/", code:"https://github.com/velz-cmd/Meridian" },
  { slug:"repodiet", name:"RepoDiet", subtitle:"Proof-carrying software maintenance", description:"Repository triage, scoped cleanup, independent verification, and review-ready receipts for AI-built software.", context:"AI-assisted codebases can accumulate unclear contracts, duplicated work, and changes that are difficult to trust. RepoDiet is designed around the maintenance workflow, not merely patch generation.", built:"RepoDiet supports repository triage, contract-scoped cleanup, isolated branches, independent verification, review-ready pull requests, and signed receipts.", architecture:"GitHub-oriented automation, A2MCP and A2A patterns, and an evidence trail make the scope and verification visible to reviewers.", decisions:["Scope changes to an explicit contract before cleanup.","Separate implementation from independent verification.","Preserve a review-ready trail instead of an opaque success state."], live:"https://skillswap-skillswap7.vercel.app/", code:"https://github.com/smokychain22/agentPass" },
  { slug:"agora-forge", name:"Agora Forge", subtitle:"Cross-chain portfolio execution", description:"An adaptive portfolio manager with cross-chain USDC execution through Circle CCTP, LI.FI, Arc, and an agent console.", context:"Agora Forge explores how a user can move from portfolio context to an explicit cross-chain USDC execution workflow.", built:"The product includes portfolio, execute, and agent-console pages, connecting adaptive portfolio context with cross-chain execution components.", architecture:"The experience separates portfolio visibility, execution, and agent control so users can understand the information, operation, and system controls independently.", decisions:["Present portfolio context before execution.","Keep cross-chain routing components legible.","Use separate surfaces for portfolio, execution, and agent control."], live:"https://circle-arc-net.vercel.app/", code:"https://github.com/Ibrahimmovic/Circle-Arc-Net" },
];

export const projectMedia: Record<string,{image:string; width:number; height:number; alt:string; services:string[]; capabilities:string[]; validation:string[]}> = {
  resolve:{image:"/assets/resolve-viewport.webp",width:1600,height:690,alt:"RESOLVE contribution evidence and funding workflow interface",services:["custom-software-development","api-integration-development"],capabilities:["Next.js product interface","Structured contribution records","Funding and treasury workflow","USDC settlement states"],validation:["Live product walkthrough","Public source repository","Explicit funding and settlement states"]},
  meridian:{image:"/assets/meridian-viewport.webp",width:1600,height:762,alt:"MERIDIAN market intelligence and strategy replay interface",services:["saas-development","web-application-development"],capabilities:["Market-data ingestion","Explainable strategy rules","Historical replay","Research and execution separation"],validation:["Live product walkthrough","Public source repository","Replayable decision workflow"]},
  repodiet:{image:"/assets/repodiet-viewport.webp",width:1600,height:765,alt:"RepoDiet repository maintenance and verification interface",services:["business-automation","api-integration-development"],capabilities:["GitHub-oriented automation","Scoped maintenance contracts","Independent verification","Review-ready evidence"],validation:["Live product walkthrough","Public source repository","Traceable verification flow"]},
  "agora-forge":{image:"/assets/agora-viewport.webp",width:1600,height:781,alt:"Agora Forge portfolio and cross-chain USDC execution interface",services:["web-application-development","api-integration-development"],capabilities:["Portfolio context","Circle CCTP integration","LI.FI routing","Cross-chain execution states"],validation:["Live product walkthrough","Public source repository","Visible portfolio-to-execution path"]},
};

export const serviceProof: Record<string,string[]> = {
  "custom-software-development":["resolve","repodiet"],
  "saas-development":["meridian","resolve"],
  "web-application-development":["meridian","agora-forge"],
  "api-integration-development":["resolve","agora-forge"],
  "business-automation":["repodiet","resolve"],
  "mvp-product-development":["meridian","agora-forge"],
  "ai-application-development":["repodiet","resolve"],
  "product-rescue":["repodiet","meridian"],
};

export const serviceFit: Record<string,{bestFor:string[]; process:string[]; outcomes:string[]}> = {
  "custom-software-development":{bestFor:["Teams replacing a manual or fragmented operating workflow","Founders with a validated problem but no dependable product yet","Existing products that need one difficult feature owned end to end"],process:["Map the user, decision, data, and integration boundary","Build the smallest complete workflow with real states","Test, deploy, document, and hand over the working system"],outcomes:["A maintainable application your team owns","Fewer manual handoffs and clearer operational state","A focused foundation that can grow with evidence"]},
  "saas-development":{bestFor:["Founders preparing a focused SaaS launch","Teams turning a prototype into an account-based product","Products that need roles, data, admin, and integrations to work together"],process:["Define the first customer job and activation path","Connect accounts, permissions, records, and operational views","Ship a measured release and prioritize from observed use"],outcomes:["A usable customer workflow rather than disconnected screens","Clear account, data, and administration boundaries","A release-ready application with an owned repository"]},
  "web-application-development":{bestFor:["Data-heavy dashboards and portals","Multi-step user workflows with permissions or integrations","Teams needing responsive interface and backend logic together"],process:["Model the workflow and every important state","Build accessible responsive interfaces against real data","Validate performance, failure handling, and deployment"],outcomes:["A fast, legible application across devices","Predictable loading, empty, validation, and error states","Frontend and application logic that behave as one product"]},
  "api-integration-development":{bestFor:["Products connecting payments, market data, GitHub, or business tools","Teams replacing copy-paste handoffs with reliable synchronization","Existing integrations that need clearer errors and observability"],process:["Document contracts, authentication, limits, and failure modes","Implement validation, retries, idempotency, and useful records","Test happy paths and recoverable failures with real systems"],outcomes:["Connected systems with explicit ownership and state","Fewer silent failures and manual reconciliations","Integration behavior the team can inspect and extend"]},
  "business-automation":{bestFor:["Recurring approval, review, triage, and handoff work","Operations held together by messages and spreadsheets","High-accountability workflows that need an evidence trail"],process:["Observe the current workflow and exception paths","Automate the repetitive steps while preserving human decisions","Measure time saved and improve the points of real friction"],outcomes:["Less repetitive work and fewer missed handoffs","One inspectable operating workflow","Controls and records appropriate to the decision"]},
  "mvp-product-development":{bestFor:["Startups testing one high-value product assumption","Founders who need a working release, not another mockup","Teams separating launch-critical scope from future ideas"],process:["Write the testable hypothesis and smallest complete journey","Build with real users, data boundaries, and essential integrations","Launch, observe, and choose the next scope from evidence"],outcomes:["A real learning loop with working software","Clear scope and explicit assumptions","Repository, deployment, and handoff your team controls"]},
  "ai-application-development":{bestFor:["Products adding AI to an existing user workflow","Teams connecting models to private data and external tools","Operations that need automation with reviewable decisions"],process:["Define the task, evidence, permissions, and human decision points","Connect models to controlled tools and structured product state","Evaluate useful and failure cases before monitored release"],outcomes:["An AI feature inside a complete product workflow","Clear fallback, review, and ownership boundaries","Observable behavior the team can test and improve"]},
  "product-rescue":{bestFor:["Founders with a promising prototype that is not release-safe","Teams inheriting an unstable or poorly documented application","Products with recurring integration, data, or deployment failures"],process:["Reproduce the critical workflow and rank failures by user and business impact","Stabilize the narrowest release path before expanding scope","Verify behavior, document ownership, and hand over a sequenced recovery plan"],outcomes:["A dependable critical path with known limitations","A smaller, evidence-backed backlog instead of an unbounded rewrite","Clear release, monitoring, and code ownership boundaries"]},
};

export const serviceFaqs: Record<string,{q:string;a:string}[]> = {
  "custom-software-development":[{q:"When does custom software make sense instead of another SaaS tool?",a:"Custom software is useful when the workflow, data, permissions, or integrations create a meaningful advantage that standard tools cannot support without heavy workarounds."},{q:"Can you work with an existing codebase?",a:"Yes. A defined feature, repair, or workflow can be delivered inside an existing codebase after its architecture, access, and acceptance conditions are understood."},{q:"Can you handle product design and backend together?",a:"Yes. The engagement can connect user flow, interface, application logic, data, integrations, testing, and deployment as one delivery path."},{q:"What should I prepare before we start?",a:"Share the user, current workflow, desired result, constraints, useful links, and any systems the product must connect to. An early brief is enough to begin scoping."}],
  "saas-development":[{q:"Can you build a SaaS product from an early idea?",a:"Yes. The first step is to define the customer job, smallest complete workflow, account model, operational needs, and assumptions the first release must test."},{q:"Can billing, roles, and admin workflows be included?",a:"Yes, when they are needed for the first useful release. They are scoped around real account, permission, support, and product requirements."},{q:"Can you improve an existing SaaS product?",a:"Yes. A project can focus on activation, a difficult feature, data architecture, integrations, performance, or a clearer operational workflow."},{q:"What does the client own?",a:"The client should control the repository, deployment, data services, and essential third-party accounts, with documentation for release and handoff."}],
  "web-application-development":[{q:"What is included beyond the frontend?",a:"A web application engagement can include data models, authorization, APIs, integrations, validation, testing, deployment, and the loading and failure states users encounter."},{q:"Can you build dashboards and internal portals?",a:"Yes. Dashboards, operational consoles, customer portals, and multi-step workflows are a strong fit when the important decisions and actions are clearly defined."},{q:"Will the application work on mobile?",a:"Responsive behavior is planned around the workflow and verified across practical mobile, tablet, and desktop sizes."},{q:"Can you integrate an existing backend?",a:"Yes. Existing APIs and services can be used after their contracts, authentication, error behavior, and ownership boundaries are reviewed."}],
  "api-integration-development":[{q:"What types of APIs can you integrate?",a:"REST APIs, webhooks, payments, identity, GitHub, market-data, blockchain, and other documented services can be connected when access and contracts are available."},{q:"How are failed webhooks or API calls handled?",a:"The design can include validation, idempotency, retries, logging, recoverable states, and visible records so failures do not disappear silently."},{q:"Can you repair an unreliable integration?",a:"Yes. The first step is to reproduce the failure, map the contract and limits, and identify whether the issue is authentication, data shape, timing, retries, or product state."},{q:"Can several systems be synchronized?",a:"Yes, with one explicit source of truth, mapped ownership, and clear conflict and recovery rules."}],
  "business-automation":[{q:"What should be automated first?",a:"Start with a repeatable workflow that has clear inputs, decisions, exceptions, and an observable result. Preserve human judgment where the decision is high risk or ambiguous."},{q:"Can you replace a spreadsheet workflow?",a:"Yes, when the spreadsheet is carrying shared state, approvals, reminders, or reporting that would benefit from roles, validation, and a clearer audit trail."},{q:"Will people still be able to review decisions?",a:"Yes. Approval points, evidence, overrides, and activity records can remain visible instead of hiding the process behind a black box."},{q:"Can the tool connect to our current software?",a:"Usually, if the existing tools expose appropriate APIs, webhooks, exports, or other supported interfaces."}],
  "mvp-product-development":[{q:"How small should an MVP be?",a:"It should be the smallest release that lets the intended user complete one meaningful workflow with enough real data and operational behavior to generate useful evidence."},{q:"Is a prototype the same as an MVP?",a:"No. A prototype can demonstrate an idea; an MVP must support a real user task, data boundary, release, and feedback loop."},{q:"Can you help decide the first-release scope?",a:"Yes. Scope is shaped around the riskiest product assumption, critical path, required integrations, acceptance conditions, and what can safely wait."},{q:"What happens after launch?",a:"Observed friction and user behavior should determine the next scope. The handoff can include the repository, deployment, documentation, and a prioritized next-step brief."}],
  "ai-application-development":[{q:"When should a workflow use an AI agent?",a:"Use an agent when the task benefits from model reasoning and controlled tool use. Deterministic rules are usually better for fixed calculations, permissions, and irreversible actions."},{q:"Can AI connect to our existing data and tools?",a:"Yes, through scoped retrieval, APIs, and explicit tool contracts, with permissions and sensitive-data boundaries designed before release."},{q:"How do you reduce incorrect AI output?",a:"Use structured inputs and outputs, retrieval where appropriate, validation, constrained tools, test sets, human review, and fallbacks rather than relying on one prompt."},{q:"Can an AI feature be added to an existing product?",a:"Yes. It can be introduced as a defined workflow with observable behavior, cost controls, and a non-AI fallback where the product requires one."}],
  "product-rescue":[{q:"Do you recommend a rewrite?",a:"Only when evidence shows the current system cannot support the required workflow safely or economically. Most rescue work should first isolate the critical path, reproduce failures, and compare focused repair with replacement."},{q:"Can you work on an AI-generated codebase?",a:"Yes. The code is treated as untrusted until contracts, tests, security boundaries, data behavior, and release steps are verified against the product workflow."},{q:"What happens during the first assessment?",a:"The assessment maps the release path, reproduces high-impact failures, reviews ownership and deployment, and produces a ranked plan with explicit assumptions and stop conditions."},{q:"Can rescue work be delivered in phases?",a:"Yes. A common sequence is assessment, critical-path stabilization, integration and data repair, release verification, then maintainability improvements that are justified by observed risk."}],
};

export const guides: Guide[] = [
  { slug:"hire-saas-developer", category:"Hiring", service:"saas-development", proof:["meridian","resolve"], title:"How to hire a SaaS developer for a product people can use", description:"A practical guide to evaluating SaaS product scope, architecture, integrations, delivery, ownership, and handoff.", intro:"Hire around a customer workflow, not a list of framework names. A strong SaaS developer should connect the account, data, interface, permissions, integrations, and deployment into one maintainable product.", sections:[
    ["Start with the customer job","Define who the first user is, what they need to accomplish, what information they need, and what changes after success. Ask the developer to identify the smallest complete path and the assumptions that still need validation."],
    ["Review the whole product boundary","Inspect more than the interface. Discuss account creation, roles, records, authorization, integrations, billing-adjacent states, operational access, and how failures will appear to a user or administrator."],
    ["Ask for evidence, not confidence","Use live projects, source code, technical decisions, and a walkthrough of a difficult state as evidence. Agree on repository ownership, environments, acceptance conditions, deployment, and handoff before the build expands."],
    ["Plan the first release","A useful first release should complete one important job with real data and meaningful feedback. Leave broad settings, secondary roles, and speculative dashboards until actual use shows they are needed."]
  ]},
  { slug:"hire-web-app-developer", category:"Hiring", service:"web-application-development", proof:["meridian","agora-forge"], title:"How to hire a web app developer without buying a collection of screens", description:"A practical guide to reviewing frontend, backend, data, integrations, testing, ownership, and deployment.", intro:"Hire a web app developer around a workflow, not a page count. The right person connects the interface a user sees with the data, rules, integrations, and deployment behind it.", sections:[
    ["Begin with the user flow","Describe who arrives, what information they need, what action they take, and what changes after success. Include loading, empty, permission, validation, and error states."],
    ["Review frontend, backend, and data together","Ask how the interface clarifies the main state and next action, how records are validated, and how authorization is enforced beyond hiding a button."],
    ["Test integration thinking","For every API or webhook, agree on inputs, expected output, failure behavior, retries, and account ownership. A happy-path demo is not a complete integration."],
    ["Make handoff part of delivery","The client should control the repository, hosting, data service, and key integrations. Document environment variables, release steps, and the acceptance conditions for the working flow."]
  ]},
  { slug:"startup-mvp-development", category:"Planning", service:"mvp-product-development", proof:["meridian","agora-forge"], title:"Startup MVP development: build a complete learning loop, not a demo", description:"A practical scope guide for defining a smallest complete workflow, choosing data and integrations, launching, and learning.", intro:"A useful MVP proves one meaningful workflow with real users. It does not need every future feature, but it needs enough interface, data, and operational reality for someone to finish the task.", sections:[
    ["Start with a testable hypothesis","Name the specific person, recurring problem, valuable outcome, and observable behavior that would change your next decision. Keep the first audience narrow."],
    ["Define the smallest complete workflow","Give the release an entry point, required information, an action, a visible result, and recovery when something goes wrong. Use real data boundaries where placeholders would hide risk."],
    ["Choose data, roles, and integrations carefully","Store only what the first workflow requires. Limit roles and connect external services only when the result would otherwise be misleading."],
    ["Avoid the demo-only MVP","Include access, incomplete input, empty data, failure states, repository ownership, and deployment. Choose the next scope from observed user friction rather than a speculative backlog."]
  ]},
  { slug:"custom-software-vs-saas", category:"Build or buy", service:"custom-software-development", proof:["resolve","repodiet"], title:"Custom software vs SaaS: a practical build-or-buy decision", description:"Use workflow fit, differentiation, ownership, integration, risk, and lifetime cost to decide whether to buy software, extend it, or build a custom system.", intro:"Buy when a mature tool supports the workflow without distorting it. Build when the workflow is strategically important, unusually specific, or depends on data and integrations that packaged software cannot support cleanly. The right answer may also be a hybrid: buy the commodity layer and build the differentiating workflow around it.", sections:[
    ["Start with workflow fit","List the user, decisions, records, exceptions, and systems involved. A SaaS tool is a strong choice when it supports those needs with modest configuration. Custom software becomes more defensible when workarounds create repeated manual handoffs, poor visibility, or compromised decisions."],
    ["Compare lifetime ownership, not only build cost","Include subscriptions, implementation, migration, integration, customization, internal administration, vendor limits, maintenance, security, support, and future change. A lower first-year price can still create a higher long-term operating burden."],
    ["Separate commodity from differentiation","Authentication, email, payments, storage, and observability are often better purchased or integrated. The workflow, data model, and decision surface that make the business distinct may be worth owning."],
    ["Choose a reversible first step","Test the decision with a narrow integration, internal tool, or critical-path release. Define what evidence would justify expanding the custom system and what conditions would send the team back to an off-the-shelf option."]
  ]},
  { slug:"saas-mvp-development-cost", category:"Cost & scope", service:"mvp-product-development", proof:["meridian","resolve"], title:"SaaS MVP development cost: what actually changes the scope", description:"A scope-first guide to the product, data, integrations, operations, and release decisions that determine the real cost of a SaaS MVP.", intro:"A responsible SaaS MVP estimate cannot come from a page count. Cost changes with the customer workflow, account and permission model, data complexity, integrations, operational tools, quality bar, and how much uncertainty must be resolved before release. Define those boundaries before discussing a number.", sections:[
    ["The customer workflow is the main cost driver","A narrow workflow with one user type and one core outcome is different from a platform with several roles, approvals, billing states, and administrative operations. Write the smallest complete journey first."],
    ["Account, data, and permissions add hidden scope","Authentication alone is not the full account system. Teams must decide invitations, organizations, roles, authorization, deletion, exports, support access, and how records are owned."],
    ["Integrations need failure handling","Payments, email, AI models, market data, and other APIs add contracts, limits, webhooks, retries, monitoring, and account ownership. Estimate the failure paths, not just the successful demo."],
    ["Estimate with acceptance conditions","Break the release into observable outcomes and include design decisions, implementation, testing, deployment, documentation, and handoff. Keep speculative secondary features outside the first estimate."]
  ]},
  { slug:"api-integration-planning", category:"Architecture", service:"api-integration-development", proof:["resolve","agora-forge"], title:"API integration planning: contracts, failures, ownership, and launch", description:"Plan an API integration around authentication, data contracts, limits, retries, webhooks, observability, testing, and operational ownership.", intro:"A dependable API integration is a product workflow with external dependencies, not a single request. Before implementation, define the contract, source of truth, authentication, limits, success state, failure behavior, and who can resolve a problem after launch.", sections:[
    ["Map the contract and source of truth","Document required inputs, returned fields, identifiers, versioning, and which system owns each record. Define how duplicates, missing data, and conflicting updates are resolved."],
    ["Design authentication and permissions","Clarify OAuth or key ownership, scopes, token storage, rotation, test environments, and whether individual users or one service account authorize the connection."],
    ["Make failures recoverable","Plan timeouts, rate limits, validation errors, retries, idempotency, webhook ordering, dead-letter handling, and a visible state that explains what needs attention."],
    ["Test operations, not only requests","Verify sandbox and production differences, logging, alerting, replay, reconciliation, privacy, and the manual process for incidents. Assign ownership for credentials and provider changes after handoff."]
  ]},
  { slug:"rescue-ai-built-web-app", category:"Product rescue", service:"product-rescue", proof:["repodiet","meridian"], published:"2026-09-27", title:"How to rescue an AI-built web app without starting over", description:"A practical method for assessing, stabilizing, testing, and releasing an AI-built or inherited web application.", intro:"Do not begin with a rewrite. First identify the product's critical workflow, reproduce its failures, establish who owns the data and deployment, and create a narrow release boundary that can be verified. Replace code only where the existing path cannot be made dependable at a reasonable cost.", sections:[
    ["Freeze the critical path","Name the first user, the one result that must work, and the states required to reach it. Pause speculative features until that path is reproducible in a controlled environment."],
    ["Turn symptoms into evidence","Record exact inputs, environment, logs, data state, expected behavior, and actual behavior for each failure. Separate product gaps from code defects, configuration problems, integration failures, and missing operational ownership."],
    ["Repair boundaries before polish","Prioritize authentication, authorization, data integrity, API contracts, error recovery, deployment, and monitoring. Visual cleanup cannot compensate for an unreliable state transition or an unknown source of truth."],
    ["Release with explicit proof","Define acceptance checks for the critical path, run them against the release build, document known limitations, and keep a rollback path. The next scope should come from observed failure and user friction, not code aesthetics."]
  ]},
  { slug:"ai-feature-vs-automation", category:"AI product", service:"ai-application-development", proof:["repodiet","resolve"], published:"2026-09-27", title:"AI feature vs automation: choose the right product architecture", description:"Decide when a workflow needs model reasoning, deterministic automation, human review, or a controlled combination of all three.", intro:"Use deterministic automation when inputs and rules are known. Use an AI feature when interpretation or generation adds real value and the result can be evaluated. Use an agent only when controlled tool use is necessary. High-impact decisions still need permissions, validation, and a human or deterministic guardrail.", sections:[
    ["Classify the decision","Write the input, allowed actions, output, cost of error, and how correctness will be judged. If the same input should always produce the same action, begin with deterministic logic."],
    ["Give models a bounded role","Use the model for classification, extraction, synthesis, or generation where ambiguity is real. Keep identity, authorization, money movement, deletion, and irreversible state changes behind explicit product rules."],
    ["Design evaluation before launch","Create representative success, edge, and failure cases. Track usefulness, incorrect output, refusal, latency, and cost. A demo prompt is not an evaluation plan."],
    ["Keep recovery visible","Show users when AI is involved, preserve source context where appropriate, provide review or correction, and define what happens when the model or an external tool is unavailable."]
  ]},
  { slug:"reliable-webhook-integration", category:"Architecture", service:"api-integration-development", proof:["resolve","agora-forge"], published:"2026-09-27", title:"Reliable webhook integration: retries, idempotency, and recovery", description:"A practical checklist for building webhook workflows that survive duplicates, delays, reordering, and provider failures.", intro:"Treat every webhook as an untrusted, repeatable event. Verify authenticity, acknowledge quickly, make processing idempotent, store enough context to retry safely, and expose failures to an operator. Delivery order and one-time execution should never be assumed unless the provider explicitly guarantees them.", sections:[
    ["Verify and acknowledge","Validate the provider signature against the raw request body, reject stale or invalid requests, and return the required success response quickly. Move slow work out of the request path when the platform supports it."],
    ["Make processing idempotent","Use the provider event ID or a stable business key to prevent duplicate effects. Store processing state and design database writes so a retry cannot charge, notify, or mutate the same record twice."],
    ["Expect delay and reordering","Fetch current provider state when an event alone is insufficient. Model transitions explicitly and avoid assuming that creation, update, and completion events arrive once or in sequence."],
    ["Build an operator recovery path","Record sanitized payload metadata, attempt count, error, and next action. Use bounded retries, a dead-letter state, alerting, replay controls, and reconciliation for events that cannot be processed automatically."]
  ]},
];

export const guideSources: Record<string,{label:string;href:string}[]> = {
  "api-integration-planning":[{label:"OWASP API Security Top 10",href:"https://owasp.org/API-Security/"},{label:"MDN HTTP semantics",href:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference"}],
  "ai-feature-vs-automation":[{label:"NIST AI Risk Management Framework",href:"https://www.nist.gov/itl/ai-risk-management-framework"}],
  "reliable-webhook-integration":[{label:"Stripe webhook guidance",href:"https://docs.stripe.com/webhooks"},{label:"GitHub webhook best practices",href:"https://docs.github.com/en/webhooks/using-webhooks/best-practices-for-using-webhooks"}],
};

export const routeList = ["services","work","guides","about","contact", ...services.map(s=>`services/${s.slug}`), ...projects.map(p=>`work/${p.slug}`), ...guides.map(g=>`guides/${g.slug}`)];
export const key = (slug:string[]) => slug.join("/");
export type Project = typeof projects[number];
